CREATE TABLE CARGA(
	CRG_CODIGO INTEGER IDENTITY,
	CRG_TIPO INTEGER NOT NULL,
	CRG_FVRSAIDA INTEGER NOT NULL,
	CRG_DTSAIDA DATE NOT NULL,
	CRG_FVRENTREGA INTEGER NOT NULL,
	CRG_DTENTREGA DATE,
	CRG_STATUS INTEGER NOT NULL,
	CRG_PROGRESSO INTEGER NOT NULL DEFAULT 0
);
GO
CREATE TABLE PRODUTOCARGA(
	PRD_CARGA INTEGER NOT NULL,
	PRD_GMPCODIGO INTEGER NOT NULL,
	PRD_CREATED_AT DATE NOT NULL
);
